### ISSUE TITLE
Learn about similar SOTA work

### ISSUE THREAD

**Issue by FangSen9000** [wyhuai/SkillMimic#2]
Your work is somewhat similar to [this one](https://www.nicklashansen.com/rlpuppeteer/), but clearly better than theirs. Nowadays, using advanced agents to control specific skills has become a widely accepted approach.

May I ask the author, in the same path as yours, what other works do you think are very good? You also can send it to my email.

**Comment by wyhuai** [comment]
Hi, you may refer to the "related work" section in the paper.

**Comment by FangSen9000** [comment]
hh
