### ISSUE TITLE
Question about humanoid robot and dataset

### ISSUE THREAD

**Issue by Shi-Qi-Li** [wyhuai/SkillMimic#6]
Hi, thanks for your amazing work and open source the code. I have some question about the humanoid robot and dataset.

1. It seems the humanoid robot is based the [UHC](https://github.com/ZhengyiLuo/UniversalHumanoidControl) but with some modifications, like extra `Spine2` joint and the geom type of some body parts are also changed. Are these modifications based on any particular reason?
2. Wheather the data across the whole dataset (ballplay-v and ballplay-m) was collected from the same player?

Any response is appreciated.

**Comment by wyhuai** [comment]
Hi, thanks for your attention. 
1. The humanoid robot for BallPlay-M is aligned with the skeleton of the Mocap system, which has an extra spine than SMPL-X(ballplay-v) skeleton. 
2. Yes, actually I am the player : ), but the resulting skeletons are different due to different mocap technology.

**Comment by Shi-Qi-Li** [comment]
> Hi, thanks for your attention.
> 
> 1. The humanoid robot for BallPlay-M is aligned with the skeleton of the Mocap system, which has an extra spine than SMPL-X(ballplay-v) skeleton.
> 2. Yes, actually I am the player : ), but the resulting skeletons are different due to different mocap technology.

Thank you very much for your reply :).
